version: "3.3"
services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
    restart: always
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`snapdrop.localhost`) && Path(`/{path:(?:((server)(/|$)).*)}`)"
      - "traefik.http.services.node.loadbalancer.server.port=3000"
  nginx:
    build:
      context: ./docker/
      dockerfile: nginx-with-openssl.Dockerfile
    image: "nginx-with-openssl"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs:/etc/ssl/certs
      - ./docker/openssl:/mnt/openssl
    env_file: ./docker/fqdn.env
    entrypoint: /mnt/openssl/create.sh
    command: [ "nginx", "-g", "daemon off;" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`snapdrop.localhost`) && !Path(`/{path:(?:((server)(/|$)).*)}`)"

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
